all:
  children:
    routers:
      hosts:
        r1:
          ansible_host: 172.100.1.2
          vars_file: host-vars/r1.yml
        r2:
          ansible_host: 172.100.1.3
          vars_file: host-vars/r2.yml
        r3:
          ansible_host: 172.100.1.4
          vars_file: host-vars/r3.yml
      vars:
        some_var_for_routers: value
        vars_file: group-vars/routers.yml
    
vr-vmx:
  children:
    routers:
