- name: Load vars for {{ hostname }}
  include_vars:
    file: "host-vars/{{ hostname }}.yml"
  register: var_result
  ignore_errors: yes

- name: Check if vars were loaded
  debug:
    msg: "Vars for {{ hostname }} were loaded successfully!"
  when: var_result is defined and not var_result.failed

- name: Render interfaces
  include_tasks: render-interface.yml
  when: var_result is defined and not var_result.failed

